export interface Currency {
  code: string;    // e.g., 'USD'
  decimals: number; // e.g., 2 for USD
  symbol: string;  // e.g., '$'
  name: string;    // e.g., 'US Dollar'
}

export const SUPPORTED_CURRENCIES: Record<string, Currency> = {
  USD: { code: 'USD', decimals: 2, symbol: '$', name: 'US Dollar' },
  EUR: { code: 'EUR', decimals: 2, symbol: '€', name: 'Euro' },
  GBP: { code: 'GBP', decimals: 2, symbol: '£', name: 'British Pound' },
  JPY: { code: 'JPY', decimals: 0, symbol: '¥', name: 'Japanese Yen' },
  CAD: { code: 'CAD', decimals: 2, symbol: 'C$', name: 'Canadian Dollar' },
  AUD: { code: 'AUD', decimals: 2, symbol: 'A$', name: 'Australian Dollar' },
  CHF: { code: 'CHF', decimals: 2, symbol: 'CHF', name: 'Swiss Franc' },
  CNY: { code: 'CNY', decimals: 2, symbol: '¥', name: 'Chinese Yuan' },
  INR: { code: 'INR', decimals: 2, symbol: '₹', name: 'Indian Rupee' },
  BRL: { code: 'BRL', decimals: 2, symbol: 'R$', name: 'Brazilian Real' },
  KRW: { code: 'KRW', decimals: 0, symbol: '₩', name: 'South Korean Won' },
  SEK: { code: 'SEK', decimals: 2, symbol: 'kr', name: 'Swedish Krona' },
  NOK: { code: 'NOK', decimals: 2, symbol: 'kr', name: 'Norwegian Krone' },
  DKK: { code: 'DKK', decimals: 2, symbol: 'kr', name: 'Danish Krone' },
  PLN: { code: 'PLN', decimals: 2, symbol: 'zł', name: 'Polish Złoty' },
  TRY: { code: 'TRY', decimals: 2, symbol: '₺', name: 'Turkish Lira' },
  RUB: { code: 'RUB', decimals: 2, symbol: '₽', name: 'Russian Ruble' },
  MXN: { code: 'MXN', decimals: 2, symbol: '$', name: 'Mexican Peso' },
  SGD: { code: 'SGD', decimals: 2, symbol: 'S$', name: 'Singapore Dollar' },
  HKD: { code: 'HKD', decimals: 2, symbol: 'HK$', name: 'Hong Kong Dollar' },
  NZD: { code: 'NZD', decimals: 2, symbol: 'NZ$', name: 'New Zealand Dollar' },
  ZAR: { code: 'ZAR', decimals: 2, symbol: 'R', name: 'South African Rand' },
  AED: { code: 'AED', decimals: 2, symbol: 'د.إ', name: 'UAE Dirham' },
  SAR: { code: 'SAR', decimals: 2, symbol: 'ر.س', name: 'Saudi Riyal' },
  ILS: { code: 'ILS', decimals: 2, symbol: '₪', name: 'Israeli Shekel' },
  THB: { code: 'THB', decimals: 2, symbol: '฿', name: 'Thai Baht' },
  MYR: { code: 'MYR', decimals: 2, symbol: 'RM', name: 'Malaysian Ringgit' },
  IDR: { code: 'IDR', decimals: 2, symbol: 'Rp', name: 'Indonesian Rupiah' },
  PHP: { code: 'PHP', decimals: 2, symbol: '₱', name: 'Philippine Peso' },
  VND: { code: 'VND', decimals: 0, symbol: '₫', name: 'Vietnamese Dong' },
  EGP: { code: 'EGP', decimals: 2, symbol: 'E£', name: 'Egyptian Pound' },
  NGN: { code: 'NGN', decimals: 2, symbol: '₦', name: 'Nigerian Naira' },
  KES: { code: 'KES', decimals: 2, symbol: 'KSh', name: 'Kenyan Shilling' },
  GHS: { code: 'GHS', decimals: 2, symbol: '₵', name: 'Ghanaian Cedi' },
  MAD: { code: 'MAD', decimals: 2, symbol: 'د.م.', name: 'Moroccan Dirham' },
  TND: { code: 'TND', decimals: 3, symbol: 'د.ت', name: 'Tunisian Dinar' },
  JOD: { code: 'JOD', decimals: 3, symbol: 'د.ا', name: 'Jordanian Dinar' },
  KWD: { code: 'KWD', decimals: 3, symbol: 'د.ك', name: 'Kuwaiti Dinar' },
  BHD: { code: 'BHD', decimals: 3, symbol: 'د.ب', name: 'Bahraini Dinar' },
  OMR: { code: 'OMR', decimals: 3, symbol: 'ر.ع.', name: 'Omani Rial' },
  QAR: { code: 'QAR', decimals: 2, symbol: 'ر.ق', name: 'Qatari Riyal' },
  LBP: { code: 'LBP', decimals: 2, symbol: 'ل.ل', name: 'Lebanese Pound' },
  IRR: { code: 'IRR', decimals: 2, symbol: '﷼', name: 'Iranian Rial' },
  PKR: { code: 'PKR', decimals: 2, symbol: '₨', name: 'Pakistani Rupee' },
  BDT: { code: 'BDT', decimals: 2, symbol: '৳', name: 'Bangladeshi Taka' },
  LKR: { code: 'LKR', decimals: 2, symbol: '₨', name: 'Sri Lankan Rupee' },
  NPR: { code: 'NPR', decimals: 2, symbol: '₨', name: 'Nepalese Rupee' },
  AFN: { code: 'AFN', decimals: 2, symbol: '؋', name: 'Afghan Afghani' },
  UZS: { code: 'UZS', decimals: 2, symbol: 'лв', name: 'Uzbekistani Som' },
  KZT: { code: 'KZT', decimals: 2, symbol: '₸', name: 'Kazakhstani Tenge' },
  GEL: { code: 'GEL', decimals: 2, symbol: '₾', name: 'Georgian Lari' },
  AMD: { code: 'AMD', decimals: 2, symbol: '֏', name: 'Armenian Dram' },
  AZN: { code: 'AZN', decimals: 2, symbol: '₼', name: 'Azerbaijani Manat' },
  BGN: { code: 'BGN', decimals: 2, symbol: 'лв', name: 'Bulgarian Lev' },
  HRK: { code: 'HRK', decimals: 2, symbol: 'kn', name: 'Croatian Kuna' },
  CZK: { code: 'CZK', decimals: 2, symbol: 'Kč', name: 'Czech Koruna' },
  HUF: { code: 'HUF', decimals: 2, symbol: 'Ft', name: 'Hungarian Forint' },
  RON: { code: 'RON', decimals: 2, symbol: 'lei', name: 'Romanian Leu' },
  RSD: { code: 'RSD', decimals: 2, symbol: 'дин.', name: 'Serbian Dinar' },
  UAH: { code: 'UAH', decimals: 2, symbol: '₴', name: 'Ukrainian Hryvnia' },
  BYN: { code: 'BYN', decimals: 2, symbol: 'Br', name: 'Belarusian Ruble' },
  MDL: { code: 'MDL', decimals: 2, symbol: 'lei', name: 'Moldovan Leu' },
  ALL: { code: 'ALL', decimals: 2, symbol: 'L', name: 'Albanian Lek' },
  MKD: { code: 'MKD', decimals: 2, symbol: 'ден', name: 'Macedonian Denar' },
  BAM: { code: 'BAM', decimals: 2, symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark' },
  ISK: { code: 'ISK', decimals: 0, symbol: 'kr', name: 'Icelandic Króna' },
  CLP: { code: 'CLP', decimals: 0, symbol: '$', name: 'Chilean Peso' },
  COP: { code: 'COP', decimals: 2, symbol: '$', name: 'Colombian Peso' },
  PEN: { code: 'PEN', decimals: 2, symbol: 'S/', name: 'Peruvian Sol' },
  UYU: { code: 'UYU', decimals: 2, symbol: '$U', name: 'Uruguayan Peso' },
  ARS: { code: 'ARS', decimals: 2, symbol: '$', name: 'Argentine Peso' },
  BOB: { code: 'BOB', decimals: 2, symbol: 'Bs', name: 'Bolivian Boliviano' },
  PYG: { code: 'PYG', decimals: 0, symbol: '₲', name: 'Paraguayan Guaraní' },
  VES: { code: 'VES', decimals: 2, symbol: 'Bs.S', name: 'Venezuelan Bolívar Soberano' },
  GYD: { code: 'GYD', decimals: 2, symbol: '$', name: 'Guyanese Dollar' },
  SRD: { code: 'SRD', decimals: 2, symbol: '$', name: 'Surinamese Dollar' },
  TTD: { code: 'TTD', decimals: 2, symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  JMD: { code: 'JMD', decimals: 2, symbol: 'J$', name: 'Jamaican Dollar' },
  BBD: { code: 'BBD', decimals: 2, symbol: '$', name: 'Barbadian Dollar' },
  BSD: { code: 'BSD', decimals: 2, symbol: '$', name: 'Bahamian Dollar' },
  BZD: { code: 'BZD', decimals: 2, symbol: 'BZ$', name: 'Belize Dollar' },
  GTQ: { code: 'GTQ', decimals: 2, symbol: 'Q', name: 'Guatemalan Quetzal' },
  HNL: { code: 'HNL', decimals: 2, symbol: 'L', name: 'Honduran Lempira' },
  NIO: { code: 'NIO', decimals: 2, symbol: 'C$', name: 'Nicaraguan Córdoba' },
  CRC: { code: 'CRC', decimals: 2, symbol: '₡', name: 'Costa Rican Colón' },
  PAB: { code: 'PAB', decimals: 2, symbol: 'B/.', name: 'Panamanian Balboa' },
  DOP: { code: 'DOP', decimals: 2, symbol: 'RD$', name: 'Dominican Peso' },
  HTG: { code: 'HTG', decimals: 2, symbol: 'G', name: 'Haitian Gourde' },
  CUP: { code: 'CUP', decimals: 2, symbol: '₱', name: 'Cuban Peso' },
  XCD: { code: 'XCD', decimals: 2, symbol: '$', name: 'East Caribbean Dollar' },
  AWG: { code: 'AWG', decimals: 2, symbol: 'ƒ', name: 'Aruban Florin' },
  ANG: { code: 'ANG', decimals: 2, symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },
  SVC: { code: 'SVC', decimals: 2, symbol: '$', name: 'Salvadoran Colón' },
  FJD: { code: 'FJD', decimals: 2, symbol: '$', name: 'Fijian Dollar' },
  PGK: { code: 'PGK', decimals: 2, symbol: 'K', name: 'Papua New Guinean Kina' },
  SBD: { code: 'SBD', decimals: 2, symbol: '$', name: 'Solomon Islands Dollar' },
  VUV: { code: 'VUV', decimals: 0, symbol: 'Vt', name: 'Vanuatu Vatu' },
  WST: { code: 'WST', decimals: 2, symbol: 'T', name: 'Samoan Tālā' },
  TOP: { code: 'TOP', decimals: 2, symbol: 'T$', name: 'Tongan Paʻanga' },
  XPF: { code: 'XPF', decimals: 0, symbol: '₣', name: 'CFP Franc' },
  XOF: { code: 'XOF', decimals: 0, symbol: 'CFA', name: 'West African CFA Franc' },
  XAF: { code: 'XAF', decimals: 0, symbol: 'FCFA', name: 'Central African CFA Franc' },
  KMF: { code: 'KMF', decimals: 0, symbol: 'CF', name: 'Comorian Franc' },
  DJF: { code: 'DJF', decimals: 0, symbol: 'Fdj', name: 'Djiboutian Franc' },
  ETB: { code: 'ETB', decimals: 2, symbol: 'Br', name: 'Ethiopian Birr' },
  ERN: { code: 'ERN', decimals: 2, symbol: 'Nfk', name: 'Eritrean Nakfa' },
  SOS: { code: 'SOS', decimals: 2, symbol: 'S', name: 'Somali Shilling' },
  UGX: { code: 'UGX', decimals: 0, symbol: 'USh', name: 'Ugandan Shilling' },
  TZS: { code: 'TZS', decimals: 2, symbol: 'TSh', name: 'Tanzanian Shilling' },
  RWF: { code: 'RWF', decimals: 0, symbol: 'R₣', name: 'Rwandan Franc' },
  BIF: { code: 'BIF', decimals: 0, symbol: 'FBu', name: 'Burundian Franc' },
  MWK: { code: 'MWK', decimals: 2, symbol: 'MK', name: 'Malawian Kwacha' },
  ZMW: { code: 'ZMW', decimals: 2, symbol: 'ZK', name: 'Zambian Kwacha' },
  BWP: { code: 'BWP', decimals: 2, symbol: 'P', name: 'Botswanan Pula' },
  NAD: { code: 'NAD', decimals: 2, symbol: '$', name: 'Namibian Dollar' },
  SZL: { code: 'SZL', decimals: 2, symbol: 'E', name: 'Swazi Lilangeni' },
  LSL: { code: 'LSL', decimals: 2, symbol: 'M', name: 'Lesotho Loti' },
  MZN: { code: 'MZN', decimals: 2, symbol: 'MT', name: 'Mozambican Metical' },
  MGA: { code: 'MGA', decimals: 2, symbol: 'Ar', name: 'Malagasy Ariary' },
  MUR: { code: 'MUR', decimals: 2, symbol: '₨', name: 'Mauritian Rupee' },
  SCR: { code: 'SCR', decimals: 2, symbol: '₨', name: 'Seychellois Rupee' },
  CVE: { code: 'CVE', decimals: 2, symbol: '$', name: 'Cape Verdean Escudo' },
  GMD: { code: 'GMD', decimals: 2, symbol: 'D', name: 'Gambian Dalasi' },
  GNF: { code: 'GNF', decimals: 0, symbol: 'FG', name: 'Guinean Franc' },
  LRD: { code: 'LRD', decimals: 2, symbol: '$', name: 'Liberian Dollar' },
  SLL: { code: 'SLL', decimals: 2, symbol: 'Le', name: 'Sierra Leonean Leone' },
  STN: { code: 'STN', decimals: 2, symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  AOA: { code: 'AOA', decimals: 2, symbol: 'Kz', name: 'Angolan Kwanza' },
  CDF: { code: 'CDF', decimals: 2, symbol: 'FC', name: 'Congolese Franc' },
  XDR: { code: 'XDR', decimals: 5, symbol: 'SDR', name: 'Special Drawing Rights' }
};

// Helper functions
export function getCurrency(code: string): Currency | undefined {
  return SUPPORTED_CURRENCIES[code.toUpperCase()];
}

export function isSupportedCurrency(code: string): boolean {
  return code.toUpperCase() in SUPPORTED_CURRENCIES;
}

export function getAllSupportedCurrencies(): Currency[] {
  return Object.values(SUPPORTED_CURRENCIES);
}

// Common currency groups for easier selection
export const MAJOR_CURRENCIES = [
  SUPPORTED_CURRENCIES.USD,
  SUPPORTED_CURRENCIES.EUR,
  SUPPORTED_CURRENCIES.GBP,
  SUPPORTED_CURRENCIES.JPY,
  SUPPORTED_CURRENCIES.CAD,
  SUPPORTED_CURRENCIES.AUD,
  SUPPORTED_CURRENCIES.CHF,
  SUPPORTED_CURRENCIES.CNY
];

export const POPULAR_CURRENCIES = [
  ...MAJOR_CURRENCIES,
  SUPPORTED_CURRENCIES.INR,
  SUPPORTED_CURRENCIES.BRL,
  SUPPORTED_CURRENCIES.KRW,
  SUPPORTED_CURRENCIES.MXN,
  SUPPORTED_CURRENCIES.SGD,
  SUPPORTED_CURRENCIES.HKD,
  SUPPORTED_CURRENCIES.NZD,
  SUPPORTED_CURRENCIES.ZAR
]; 