// Base paths
export const BASE = {
  HOME: '/',
  APP: '/app',
  STUDIO: '/studio',
  AUTH: '/auth',
  ADMIN: '/admin'
} as const;

// Feature bases
export const NEWS = {
  ROOT: 'news',
  SUBPATHS : {
    TRENDING: 'trending',
    MY_FEED: 'feed',
    DISCOVER: 'discover'
  },
  CREATE: 'create',
  EDIT: 'edit',
  VIEW: ':id'
} as const;

export const CHANNEL = {
  ROOT: 'channels',
  CREATE: 'create',
  EDIT: 'edit',
  VIEW: ':id',
} as const;

export const POLL = {
  ROOT: 'polls',
  CREATE: 'create',
  EDIT: 'edit',
  VIEW: ':id'
} as const;

export const ACCOUNT = {
  ROOT: 'account',
  PROFILE: 'profile',
  PAYMENT_METHODS: 'payment-methods',
  SUBSCRIPTIONS: 'subscriptions'
} as const;

export const EXPENSE_ORDER = {
  ROOT: 'expense-orders',
  CREATE: 'create',
  EDIT: 'edit',
  VIEW: ':id'
} as const;

export const SEARCH = {
  ROOT: 'search'
} as const;

// Admin feature bases
export const ADMIN = {
  ROOT: 'admin',
  DASHBOARD: 'dashboard',
  USERS: 'users',
  CHANNELS: 'channels',
  NEWS: 'news',
  POLLS: 'polls',
  EXPENSE_ORDERS: 'expense-orders',
  PAYOUTS: 'payouts',
  TAGS: 'tags',
  SUBSCRIPTIONS: 'subscriptions',
  ANALYTICS: 'analytics',
  SETTINGS: 'settings'
} as const;

export const SUBSCRIPTION = {
  ROOT: 'subscriptions',
  MANAGEMENT: 'management',
  ANALYTICS: 'analytics',
  REVENUE: 'revenue'
} as const;

export const USER_MANAGEMENT = {
  ROOT: 'users',
  LIST: 'list',
  VIEW: ':id',
  EDIT: ':id/edit',
  ROLES: 'roles'
} as const;

export const CHANNEL_MANAGEMENT = {
  ROOT: 'channels',
  LIST: 'list',
  VIEW: ':id',
  EDIT: ':id/edit',
  ANALYTICS: 'analytics'
} as const;

const ENV_BASE = import.meta.env.BASE_URL.replace(/\/$/, ''); // Remove trailing slash if present

// Absolute paths
export const PATHS = {
  // Base
  HOME: `${ENV_BASE}${BASE.HOME}`,
  // Auth
  LOGIN: `${ENV_BASE}${BASE.AUTH}/login`,
  SIGNUP: `${ENV_BASE}${BASE.AUTH}/signup`,
  POST_SIGNUP: `${ENV_BASE}${BASE.AUTH}/welcome`,
  
  // App
  APP_ROOT: `${ENV_BASE}${BASE.APP}`,
  APP_NEWS: `${ENV_BASE}${BASE.APP}/${NEWS.ROOT}`,
  APP_NEWS_TRENDING: `${ENV_BASE}${BASE.APP}/${NEWS.ROOT}/trending`,
  APP_NEWS_MY_FEED: `${ENV_BASE}${BASE.APP}/${NEWS.ROOT}/feed`,
  APP_NEWS_DISCOVER: `${ENV_BASE}${BASE.APP}/${NEWS.ROOT}/discover`,
  APP_NEWS_VIEW: `${ENV_BASE}${BASE.APP}/${NEWS.ROOT}/:id`,
  APP_CHANNELS: `${ENV_BASE}${BASE.APP}/${CHANNEL.ROOT}`,
  APP_CHANNEL_VIEW: `${ENV_BASE}${BASE.APP}/${CHANNEL.ROOT}/:channelId`,
  APP_POLL_LIST: `${ENV_BASE}${BASE.APP}/${POLL.ROOT}`,
  APP_POLL_VIEW: `${ENV_BASE}${BASE.APP}/${POLL.ROOT}/:id`,
  APP_EXPLORE: `${ENV_BASE}${BASE.APP}/explore`,
  APP_SUBSCRIPTIONS: `${ENV_BASE}${BASE.APP}/subscriptions`,
  APP_POLLS: `${ENV_BASE}${BASE.APP}/${POLL.ROOT}`,
  APP_SEARCH: `${ENV_BASE}${BASE.APP}/${SEARCH.ROOT}`,
  APP_ACCOUNT: `${ENV_BASE}${BASE.APP}/${ACCOUNT.ROOT}`,
  APP_ACCOUNT_PROFILE: `${ENV_BASE}${BASE.APP}/${ACCOUNT.ROOT}/${ACCOUNT.PROFILE}`,
  APP_ACCOUNT_PAYMENT_METHODS: `${ENV_BASE}${BASE.APP}/${ACCOUNT.ROOT}/${ACCOUNT.PAYMENT_METHODS}`,
  APP_ACCOUNT_SUBSCRIPTIONS: `${ENV_BASE}${BASE.APP}/${ACCOUNT.ROOT}/${ACCOUNT.SUBSCRIPTIONS}`,
  APP_EXPENSE_ORDERS: `${ENV_BASE}${BASE.APP}/${EXPENSE_ORDER.ROOT}`,
  APP_EXPENSE_ORDER_VIEW: `${ENV_BASE}${BASE.APP}/${EXPENSE_ORDER.ROOT}/:id`,
  
  // Studio
  STUDIO_ROOT: `${ENV_BASE}${BASE.STUDIO}`,
  STUDIO_NEWS: `${ENV_BASE}${BASE.STUDIO}/${NEWS.ROOT}`,
  STUDIO_NEWS_CREATE: `${ENV_BASE}${BASE.STUDIO}/${NEWS.ROOT}/${NEWS.CREATE}`,
  STUDIO_NEWS_EDIT: `${ENV_BASE}${BASE.STUDIO}/${NEWS.ROOT}/${NEWS.EDIT}/:id`,
  STUDIO_NEWS_VIEW: `${ENV_BASE}${BASE.STUDIO}/${NEWS.ROOT}/:id`,
  STUDIO_CHANNELS: `${ENV_BASE}${BASE.STUDIO}/${CHANNEL.ROOT}`,
  STUDIO_CHANNEL_CREATE: `${ENV_BASE}${BASE.STUDIO}/${CHANNEL.ROOT}/${CHANNEL.CREATE}`,
  STUDIO_CHANNEL_EDIT: `${ENV_BASE}${BASE.STUDIO}/${CHANNEL.ROOT}/${CHANNEL.EDIT}/:channelId`,
  STUDIO_CHANNEL_VIEW: `${ENV_BASE}${BASE.STUDIO}/${CHANNEL.ROOT}/:channelId`,
  STUDIO_POLLS: `${ENV_BASE}${BASE.STUDIO}/${POLL.ROOT}`,
  STUDIO_POLL_CREATE: `${ENV_BASE}${BASE.STUDIO}/${POLL.ROOT}/${POLL.CREATE}`,
  STUDIO_POLL_EDIT: `${ENV_BASE}${BASE.STUDIO}/${POLL.ROOT}/${POLL.EDIT}/:id`,
  STUDIO_POLL_VIEW: `${ENV_BASE}${BASE.STUDIO}/${POLL.ROOT}/:id`,
  STUDIO_SEARCH: `${ENV_BASE}${BASE.STUDIO}/${SEARCH.ROOT}`,
  STUDIO_EXPENSE_ORDERS: `${ENV_BASE}${BASE.STUDIO}/${EXPENSE_ORDER.ROOT}`,
  STUDIO_EXPENSE_ORDER_CREATE: `${ENV_BASE}${BASE.STUDIO}/${EXPENSE_ORDER.ROOT}/${EXPENSE_ORDER.CREATE}`,
  STUDIO_EXPENSE_ORDER_EDIT: `${ENV_BASE}${BASE.STUDIO}/${EXPENSE_ORDER.ROOT}/${EXPENSE_ORDER.EDIT}/:id`,
  STUDIO_EXPENSE_ORDER_VIEW: `${ENV_BASE}${BASE.STUDIO}/${EXPENSE_ORDER.ROOT}/:id`,

  // Admin
  ADMIN_ROOT: `${ENV_BASE}${BASE.ADMIN}`,
  ADMIN_DASHBOARD: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.DASHBOARD}`,
  ADMIN_USERS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.USERS}`,
  ADMIN_USER_LIST: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.USERS}/${USER_MANAGEMENT.LIST}`,
  ADMIN_USER_VIEW: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.USERS}/${USER_MANAGEMENT.VIEW}`,
  ADMIN_USER_EDIT: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.USERS}/${USER_MANAGEMENT.EDIT}`,
  ADMIN_USER_ROLES: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.USERS}/${USER_MANAGEMENT.ROLES}`,
  ADMIN_CHANNELS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.CHANNELS}`,
  ADMIN_CHANNEL_LIST: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.CHANNELS}/${CHANNEL_MANAGEMENT.LIST}`,
  ADMIN_CHANNEL_VIEW: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.CHANNELS}/${CHANNEL_MANAGEMENT.VIEW}`,
  ADMIN_CHANNEL_EDIT: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.CHANNELS}/${CHANNEL_MANAGEMENT.EDIT}`,
  ADMIN_CHANNEL_ANALYTICS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.CHANNELS}/${CHANNEL_MANAGEMENT.ANALYTICS}`,
  ADMIN_NEWS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.NEWS}`,
  ADMIN_POLLS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.POLLS}`,
  ADMIN_EXPENSE_ORDERS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.EXPENSE_ORDERS}`,
  ADMIN_PAYOUTS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.PAYOUTS}`,
  ADMIN_TAGS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.TAGS}`,
  ADMIN_SUBSCRIPTIONS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.SUBSCRIPTIONS}`,
  ADMIN_SUBSCRIPTION_MANAGEMENT: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.SUBSCRIPTIONS}/${SUBSCRIPTION.MANAGEMENT}`,
  ADMIN_SUBSCRIPTION_ANALYTICS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.SUBSCRIPTIONS}/${SUBSCRIPTION.ANALYTICS}`,
  ADMIN_SUBSCRIPTION_REVENUE: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.SUBSCRIPTIONS}/${SUBSCRIPTION.REVENUE}`,
  ADMIN_ANALYTICS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.ANALYTICS}`,
  ADMIN_SETTINGS: `${ENV_BASE}${BASE.ADMIN}/${ADMIN.SETTINGS}`,
} as const;

export type PathsType = typeof PATHS;